language: python
python:
  - 2.7
matrix:
  include:
    - os: osx
      language: generic
      env:
      before_install:
      - brew upgrade
      - brew install capstone graphviz ocaml ocamlbuild camlp5 opam
      - pip install --upgrade pip
      - pip install virtualenv
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - avsm
    packages:
    - gcc-4.8
    - g++-4.8
    - clang-3.4
    - build-essential
    - debootstrap
    - debian-archive-keyring
    - libjpeg-dev
    - zlib1g-dev
    - unzip
    - wget
    - graphviz
    - curl
    - libcurl4-gnutls-dev
    - libgmp-dev
    - libssl-dev
    - libzip-dev
    - llvm
    - llvm-3.4-dev
    - m4
    - ocaml
    - ocaml-base
    - ocaml-base-nox
    - ocaml-compiler-libs
    - ocaml-native-compilers
    - ocaml-nox
    - camlp4-extra
    - time
    - aspcud
    - dejagnu
    - jq
    - opam
    - libicu48
    - libicu-dev
    - lib32icu48
    - lib32icu-dev
	  - phantomjs
    - software-properties-common
    - python-dev
    - python-pip
    - python-virtualenv
env:
  - CXX=g++-4.8 CC=gcc-4.8
install:
  - ./install.sh
script:
  - ./run_tests.sh
  - ./run_tests_static.sh
