sudo: true

language: python

python:
  - 2.7

matrix:
  include:
    - os: osx
      language: generic
      env:
      before_install:
      - brew upgrade
      - brew install capstone graphviz
      - pip install --upgrade pip
      - pip install virtualenv

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - build-essential
    - debootstrap
    - debian-archive-keyring
    - libjpeg-dev
    - zlib1g-dev
    - unzip
    - wget
    - graphviz
    - curl
    - python-dev
    - python-pip
    - python-virtualenv

env:
  - CXX=g++-4.8 CC=gcc-4.8

install:
  - ./install.sh

script:
  - ./run_tests.sh
  - ./run_tests_static.sh
