sudo: true

language: python

python:
  - 2.7

matrix:
  include:
    - os: linux
      env: CXX=g++-4.8 CC=gcc-4.8
    - os: osx
      language: generic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - build-essential
    - debootstrap
    - debian-archive-keyring
    - libjpeg-dev
    - zlib1g-dev
    - unzip
    - wget
    - graphviz
    - curl
    - python-dev
    - python-pip
    - python-virtualenv

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install capstone graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install virtualenv; fi

install:
  - ./install.sh

script:
  - ./run_tests.sh
  - ./run_tests_static.sh
